name: CI

on:
  push:
    branches:
      - main
    paths:
      - "airflow-*/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect changed directories
        id: set-matrix
        run: |
          CHANGED_DIRS=()
          for path in airflow-*; do
            if git diff --name-only HEAD^ HEAD | grep -qE "^$path/"; then
              CHANGED_DIRS+=("$path")
            fi
          done
          echo "matrix=$(echo ${CHANGED_DIRS[@]} | jq -Rc 'split(" ")')" >> $GITHUB_OUTPUT

  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != '[]'
    name: Build and Push Docker Image for ${{ matrix.directory }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{fromJson(needs.detect-changes.outputs.matrix)}}
    steps:
      - name: Check out code again
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.directory }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.directory }}:latest

      - name: Notify Slack
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          -d '{
                  "channel": "zerohertz",
                  "text": ":tada: [GitHub Actions] Build [${{ secrets.DOCKER_USERNAME }}/${{ matrix.directory }}:latest](https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/${{ matrix.directory }}/general) Completed.",
                  "username": "GitHub",
                  "icon_url": "https://github-production-user-asset-6210df.s3.amazonaws.com/42334717/286302856-85c52548-7217-4412-a5cb-a066f588fc13.png",
              }'
